### ISSUE TITLE
Issue with Underscore Arbitrary Modifier in Tailwind CSS

### ISSUE THREAD

**Issue by AkramElganiny** [green-labs/res_tailwindcss#32]
I'm encountering an issue when trying to use the underscore arbitrary modifier to style the descending a of a div. Below is the code I'm using:

```
<div
  className={cx([
     %twc(
          "tw-overflow-hidden tw-transition-[padding-top] tw-ease-out tw-duration-[400ms] [&_a]:tw-mt-4"
      ),
      switch state {
      | true => %twc("tw-p-20")
      | false => %twc("tw-max-h-0")
      },
   ])}
```
However, it results in the following error:

```
 104 ┆ className={cx([
  105 ┆   %twc(
  106 ┆     "tw-overflow-hidden tw-transition-[padding-top] tw-ease-out tw-dur
      ┆ ation-[400ms] [&_a]:tw-mt-4"
  107 ┆   ),

  Class name not found: [&_a]:tw-mt-4

FAILED: cannot make progress due to previous errors.
>>>> Finish compiling(exit: 1)
```
### Steps to Reproduce:

1. Add the above code to a res component. (remove the prefix `tw-` if not configured)
2. Ensure Tailwind CSS watcher is running to build the new classes.
3. Observe the error message during compilation.

### Additional Information:
- Tailwind CSS reference: [Tailwind CSS Documentation](https://tailwindcss.com/docs/hover-focus-and-other-states#using-arbitrary-variants)
- Other selectors like > are working as expected.
- Manually modifying the .bs.js output file with the underscore modifier works as expected.
- It appears the issue might be with the ppx not recognizing this modifier.

Any assistance or guidance on how to resolve this issue would be greatly appreciated. Thank you!

**Comment by mununki** [comment]
Hi, thank you for reporting the issue.
Can you copy and paste the `[&_a]:tw-mt-4` part from the generated tailwind css file? Is it actually existing inside the css file?

**Comment by AkramElganiny** [comment]
Hi,
Yes, it's created:

```
.\[\&_a\]\:tw-mt-4 a {
  margin-top: 4px
}
```

**Comment by mununki** [comment]
Actually, this issue is caused by not supporting the descendant combinator by parser.
#33 fixes this issue.

**Comment by mununki** [comment]
Published to npm. Can you test with v0.1.13? https://www.npmjs.com/package/@greenlabs/res-tailwindcss/v/0.1.13
Please reopen the issue if you have any further issue.
